import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { AiTestGenerator } from '../ai/generator.js';
import { PageAnalyzer } from '../crawler/page-analyzer.js';
import type {
  AppConfig,
  GenerateOptions,
  GeneratedTestFile,
  PageAnalysis,
  TestScenario,
} from '../types/index.js';
import { rootLogger } from '../utils/logger.js';
import { formatTypeScript } from './formatter.js';

/**
 * High-level orchestrator that ties the crawler, AI generator, formatter,
 * and disk writer together.
 *
 * Lifecycle:
 *   const writer = new TestWriter(config);
 *   await writer.start();
 *   const result = await writer.generate({ url, scenarios: 5 });
 *   await writer.stop();
 */
export class TestWriter {
  private readonly config: AppConfig;
  private readonly analyzer: PageAnalyzer;
  private readonly generator: AiTestGenerator;
  private readonly log = rootLogger.child('test-writer');
  private started = false;

  constructor(config: AppConfig) {
    this.config = config;
    this.analyzer = new PageAnalyzer(config);
    this.generator = new AiTestGenerator(config);
    this.log.setLevel(config.logLevel);
  }

  async start(): Promise<void> {
    if (this.started) {
      return;
    }
    await this.analyzer.start();
    this.started = true;
  }

  async stop(): Promise<void> {
    if (!this.started) {
      return;
    }
    await this.analyzer.stop();
    this.started = false;
  }

  async generate(options: GenerateOptions): Promise<GeneratedTestFile> {
    if (!this.started) {
      throw new Error('TestWriter not started. Call start() first.');
    }

    const scenarioCount = options.scenarios ?? 5;
    const generatedAt = new Date().toISOString();

    const analysis = await this.analyzer.analyze({ url: options.url });
    const scenarios = await this.generator.designScenarios(
      analysis,
      scenarioCount,
      options.scenarioHints ?? [],
    );

    const rawCode = await this.generator.generateTestCode({
      url: options.url,
      analysis,
      scenarios,
      generatedAt,
    });

    const fileName = options.fileName ?? buildFileName(analysis);
    const outputDir = options.outputDir ?? this.config.generatedTestsDir;
    const filePath = resolveOutputPath(outputDir, fileName);

    const fullCode = injectHeader({
      code: rawCode,
      sourceUrl: options.url,
      model: this.generator.model,
      generatedAt,
      scenarios,
    });
    const formatted = await formatTypeScript(fullCode, filePath);

    if (options.dryRun !== true) {
      await mkdir(dirname(filePath), { recursive: true });
      await writeFile(filePath, formatted, 'utf8');
      this.log.info(`Wrote ${scenarios.length} scenarios to ${filePath}`);
    } else {
      this.log.info(`[dry-run] Would write ${scenarios.length} scenarios to ${filePath}`);
    }

    return {
      fileName,
      filePath,
      code: formatted,
      scenarios,
      sourceUrl: options.url,
      model: this.generator.model,
      generatedAt,
    };
  }
}

function resolveOutputPath(outputDir: string, fileName: string): string {
  const dir = isAbsolute(outputDir) ? outputDir : resolve(process.cwd(), outputDir);
  return join(dir, fileName);
}

function buildFileName(analysis: PageAnalysis): string {
  const slugBase = analysis.title || new URL(analysis.url).hostname;
  const slug = slugify(slugBase) || 'page';
  const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  return `${slug}-${stamp}.spec.ts`;
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function injectHeader(args: {
  code: string;
  sourceUrl: string;
  model: string;
  generatedAt: string;
  scenarios: TestScenario[];
}): string {
  const { code, sourceUrl, model, generatedAt, scenarios } = args;
  const headerLine = '/**';
  if (code.startsWith(headerLine)) {
    return code;
  }
  const scenarioList = scenarios.map((s, i) => ` *   ${i + 1}. ${s.name}`).join('\n');
  const banner = `/**
 * AUTO-GENERATED by playwright-ai-testgen.
 *
 * Source URL : ${sourceUrl}
 * Model      : ${model}
 * Generated  : ${generatedAt}
 *
 * Scenarios:
${scenarioList}
 *
 * Edits to this file will be lost on regeneration.
 */
`;
  return `${banner}\n${code}`;
}
